const KEY='pokerCampeonatoJorgeV3',OLDKEY2='pokerCampeonatoJorgeV2',OLDKEY1='pokerCampeonatoJorgeV1';
function init(){return{players:Array.from({length:12},(_,i)=>({id:i+1,name:`Jogador ${i+1}`,active:true})),events:[]}}
function migrate(s){if(!s)return init();s.players=s.players||init().players;s.events=(s.events||[]).map(e=>({...e,id:e.id||String(Date.now()+Math.random())}));return s}
let state;try{state=migrate(JSON.parse(localStorage.getItem(KEY))||JSON.parse(localStorage.getItem(OLDKEY2))||JSON.parse(localStorage.getItem(OLDKEY1)))}catch{state=init()}let editingId=null,placeMode='wins';
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}),num=n=>Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:0}),pts=(r,natal)=>((+r.received||0)-(+r.additional||0))*(natal?2:1);
function eventStandings(e){return e.results.map(r=>({...r,points:pts(r,e.christmas)})).sort((a,b)=>b.points-a.points)}
function stats(){const map={};state.players.forEach(p=>map[p.id]={...p,points:0,played:0,received:0,additional:0,wins:0,seconds:0,thirds:0,podiums:0,best:null,worst:null});state.events.forEach(e=>{const st=eventStandings(e);st.forEach((r,idx)=>{let p=map[r.playerId];if(!p)return;p.points+=r.points;p.played++;p.received+=+r.received||0;p.additional+=+r.additional||0;p.best=p.best===null?r.points:Math.max(p.best,r.points);p.worst=p.worst===null?r.points:Math.min(p.worst,r.points);if(idx===0)p.wins++;if(idx===1)p.seconds++;if(idx===2)p.thirds++;if(idx<=2)p.podiums++})});return Object.values(map)}
function ranking(){return stats().sort((a,b)=>b.points-a.points||b.wins-a.wins||b.seconds-a.seconds||b.thirds-a.thirds)}
function cashTotals(e){const participants=e.results.length,initial=participants*100,additional=e.results.reduce((s,r)=>s+(+r.additional||0),0),collected=initial+additional,paid=e.results.reduce((s,r)=>s+(+r.received||0),0);return{participants,initial,additional,collected,paid,diff:collected-paid}}
function formResults(){return[...document.querySelectorAll('.playerRow')].map(row=>row.querySelector('.part').checked?{playerId:+row.dataset.id,additional:+row.querySelector('.additional').value||0,received:+row.querySelector('.received').value||0}:null).filter(Boolean)}
function renderRanking(){const el=document.getElementById('rankingList');if(!state.events.length){el.innerHTML='<div class="empty">Nenhuma etapa registrada ainda.</div>';return}el.innerHTML=`<div class="rankRow small"><div>Pos</div><div>Jogador</div><div class="pts">Pontos</div><div class="center">1º</div><div class="center">2º</div><div class="center">3º</div></div>`+ranking().map((p,i)=>`<div class="rankRow"><div class="name">${i+1}º</div><div><div class="name">${p.name}</div><div class="small">${p.played} etapa(s) · pódios ${p.podiums} · recebeu ${brl(p.received)}</div></div><div class="pts ${p.points<0?'neg':'pos'}">${num(p.points)}</div><div class="center">${p.wins}</div><div class="center">${p.seconds}</div><div class="center">${p.thirds}</div></div>`).join('')}
function renderPlacement(){const label={wins:'Vitórias',seconds:'2º lugares',thirds:'3º lugares',podiums:'Pódios'}[placeMode];const arr=stats().sort((a,b)=>b[placeMode]-a[placeMode]||b.points-a.points);document.getElementById('placementList').innerHTML=`<div class="placeRow small"><div>Pos</div><div>Jogador</div><div class="pts">${label}</div></div>`+arr.map((p,i)=>`<div class="placeRow"><div class="name">${i+1}º</div><div><div class="name">${p.name}</div><div class="small">${num(p.points)} pontos · ${p.played} etapa(s)</div></div><div class="pts">${p[placeMode]}</div></div>`).join('')}
function renderForm(prefill=null){document.getElementById('resultsForm').innerHTML=state.players.filter(p=>p.active).map(p=>{const r=prefill?.results?.find(x=>x.playerId===p.id);return`<div class="playerRow" data-id="${p.id}"><label class="check"><input type="checkbox" class="part" ${r?'checked':''}><span class="name">${p.name}</span></label><label>Recompras<input class="additional" type="number" inputmode="numeric" min="0" step="50" value="${r?.additional||0}"></label><label>Recebido<input class="received" type="number" inputmode="numeric" min="0" step="50" value="${r?.received||0}"></label></div>`}).join('');document.querySelectorAll('.playerRow input').forEach(x=>x.addEventListener('input',renderCashCheck));renderCashCheck()}
function renderCashCheck(){const c=cashTotals({results:formResults()}),cls=c.diff===0?'ok':'bad',status=c.diff===0?'CAIXA OK':'DIVERGÊNCIA';document.getElementById('cashCheck').innerHTML=`<div class="cashGrid"><div>Participantes</div><div>${c.participants}</div><div>Cacifes iniciais</div><div>${brl(c.initial)}</div><div>Compras adicionais</div><div>${brl(c.additional)}</div><div>Total arrecadado</div><div>${brl(c.collected)}</div><div>Total distribuído</div><div>${brl(c.paid)}</div><div>Diferença</div><div class="${cls}">${brl(c.diff)}</div><div>Status</div><div class="${cls}">${status}</div></div>`}
function renderPlayers(){document.getElementById('playersEdit').innerHTML=state.players.map(p=>`<div class="editRow" data-id="${p.id}"><label class="check"><input class="activePlayer" type="checkbox" ${p.active?'checked':''}></label><input class="playerName" value="${String(p.name).replaceAll('"','&quot;')}"></div>`).join('')}
function renderHistory(){const el=document.getElementById('historyList');if(!state.events.length){el.innerHTML='<div class="empty">Nenhuma etapa registrada ainda.</div>';return}el.innerHTML=[...state.events].reverse().map(e=>{const c=cashTotals(e),st=eventStandings(e),total=st.reduce((s,r)=>s+r.points,0),lines=st.map((r,idx)=>{const p=state.players.find(x=>x.id===r.playerId);return`<div class="small">${idx+1}º ${p?.name||'Jogador'}: ${num(r.points)} pts · recebeu ${brl(r.received)} · recompras ${brl(r.additional)}</div>`}).join('');return`<div class="eventRow"><div class="eventHead"><div><div class="name">${e.name}${e.christmas?'<span class="badge">Natal 2x</span>':''}</div><div class="small">${e.date||'Sem data'} · ${e.results.length} jogador(es) · ${num(total)} pontos · caixa ${c.diff===0?'OK':'divergente'}</div></div><div class="eventActions"><button class="editBtn" onclick="editEvent('${e.id}')">Editar</button><button class="deleteBtn" onclick="deleteEvent('${e.id}')">Excluir</button></div></div><div class="eventStandings">${lines}</div></div>`}).join('')}
function render(){renderRanking();renderPlacement();renderPlayers();renderHistory();if(!editingId)renderForm()}
function openTab(tab){document.querySelectorAll('.tabBtn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-tab="${tab}"]`).classList.add('active');document.getElementById(tab).classList.add('active')}
document.querySelectorAll('.tabBtn').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));document.querySelectorAll('.placeBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.placeBtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');placeMode=b.dataset.place;renderPlacement()});document.getElementById('eventDate').valueAsDate=new Date();
function clearForm(){editingId=null;document.getElementById('formTitle').textContent='Registrar etapa';document.getElementById('cancelEdit').classList.add('hidden');document.getElementById('eventDate').valueAsDate=new Date();document.getElementById('eventName').value='';document.getElementById('christmas').checked=false;renderForm()}
window.editEvent=function(id){const e=state.events.find(x=>String(x.id)===String(id));if(!e)return;editingId=e.id;document.getElementById('formTitle').textContent='Editar etapa';document.getElementById('cancelEdit').classList.remove('hidden');document.getElementById('eventDate').value=e.date||'';document.getElementById('eventName').value=e.name||'';document.getElementById('christmas').checked=!!e.christmas;renderForm(e);openTab('nova')}
window.deleteEvent=function(id){const e=state.events.find(x=>String(x.id)===String(id));if(!e)return;if(confirm(`Excluir ${e.name}? O ranking será recalculado.`)){state.events=state.events.filter(x=>String(x.id)!==String(id));if(String(editingId)===String(id))clearForm();save();render()}}
document.getElementById('cancelEdit').onclick=clearForm;
document.getElementById('saveEvent').onclick=()=>{const results=formResults();if(!results.length){alert('Marque pelo menos um participante.');return}const obj={id:editingId||String(Date.now()),date:document.getElementById('eventDate').value,name:document.getElementById('eventName').value||(editingId?'Etapa editada':`Etapa ${state.events.length+1}`),christmas:document.getElementById('christmas').checked,results};if(editingId){const ix=state.events.findIndex(e=>String(e.id)===String(editingId));state.events[ix]=obj}else state.events.push(obj);save();clearForm();render();openTab('ranking')};
document.getElementById('savePlayers').onclick=()=>{document.querySelectorAll('.editRow').forEach(row=>{let p=state.players.find(x=>x.id==row.dataset.id);p.name=row.querySelector('.playerName').value||`Jogador ${p.id}`;p.active=row.querySelector('.activePlayer').checked});save();render();alert('Jogadores salvos.')};
document.getElementById('resetAll').onclick=()=>{if(confirm('Apagar todos os dados?')){state=init();editingId=null;save();clearForm();render()}};
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='backup-campeonato-poker.json';a.click();URL.revokeObjectURL(url)};
document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();
document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const imported=migrate(JSON.parse(reader.result));if(confirm('Importar este backup e substituir os dados atuais?')){state=imported;save();clearForm();render();alert('Backup importado.')}}catch{alert('Arquivo de backup inválido.')}};reader.readAsText(f)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
